# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  webAppName: 'StoicDreams.SampleWebsite'

stages:
- stage: Alpha
  jobs:
  - job: BlazorUI
    displayName: 'Build and Publish Blazor UI Framework'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      buildConfiguration: 'Release'
    steps:
      - task: NuGetToolInstaller@1
        inputs:
          versionSpec: '6.x'
          checkLatest: true
      - task: UseDotNet@2
        displayName: 'Load the SDK'
        inputs:
          packageType: 'sdk'
          version: '7.x'
          includePreviewVersions: true
      - task: DotNetCoreCLI@2
        displayName: 'Restore nuget packages'
        inputs:
          command: 'restore'
          projects: |
            **/*.BlazorUI.csproj
            **/*.BuildTests.csproj
          includeNuGetOrg: true
      - task: DotNetCoreCLI@2
        displayName: 'Build and pack the project'
        inputs:
          command: 'build'
          projects: |
            **/*.BlazorUI.csproj
            **/*.BuildTests.csproj
      - task: VisualStudioTestPlatformInstaller@1
      - task: DotNetCoreCLI@2
        displayName: 'Run Build Tests'
        inputs:
          command: 'test'
          projects: '**/*.BuildTests.csproj'
          arguments: '--configuration $(buildConfiguration) --no-restore --collect: "XPlat Code Coverage"'
          publishTestResults: true,
          nobuild: true
      - script: "dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.5.8"
        displayName: "Install ReportGenerator tool"
      - script: 'reportgenerator -reports:**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"'
        displayName: "Create reports"
      - task: PublishCodeCoverageResults@1
        displayName: "Publish code coverage report"
        inputs:
          codeCoverageTool: "Cobertura"
          summaryFileLocation: "$(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml"
      - task: Bash@3
        displayName: 'Push package to nuget store'
        inputs:
          targetType: inline
          script: dotnet nuget push --api-key $(NugetApiKey) --skip-duplicate --source $(NugetSource) '$(Agent.BuildDirectory)\NugetPackages\StoicDreams.BlazorUI.*.nupkg' > nugetpush.txt; echo $(cat nugetpush.txt)
      - task: Bash@3
        displayName: 'Echo version number.'
        inputs:
          targetType: inline
          script: pushResult=$(cat nugetpush.txt); re=".*StoicDreams\.BlazorUI\.([0-9\.]+)\.nupkg.*";if [[ $pushResult =~ $re ]]; then echo ${BASH_REMATCH[1]}; fi

  - job: DelayToAllowNugetTimeToPublish
    displayName: 'Give Nuget.org time to process publishing'
    dependsOn:
    - BlazorUI
    condition: succeeded()
    pool: Server
    steps:
    - task: Delay@1
      inputs:
        delayForMinutes: '5'


  - job: BlazorUIWebsite
    displayName: 'Build and Publish Blazor UI Sample Website'
    dependsOn:
    - DelayToAllowNugetTimeToPublish
    condition: succeeded()
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      buildConfiguration: 'Release'
    steps:
      - task: UseDotNet@2
        displayName: 'Set .NET SDK Version'
        inputs:
          packageType: 'sdk'
          version: '7.x'
          includePreviewVersions: true
      - task: DotNetCoreCLI@2
        displayName: 'Restore Nuget Dependencies'
        inputs:
          command: 'restore'
          projects: '**/*SampleWebsite.csproj'
          includeNuGetOrg: true
      - task: DotNetCoreCLI@2
        displayName: 'Build Solution'
        inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration)'
          projects: '**/*SampleWebsite.csproj'
      - task: CmdLine@2
        displayName: 'Publish Sample Website'
        inputs:
          script: 'C:\hostedtoolcache\windows\dotnet\dotnet.exe publish $(System.DefaultWorkingDirectory)/$(webAppName)/$(webAppName).csproj --configuration $(buildConfiguration) --no-restore --no-build --self-contained true /p:LinkDuringPublish=false'
      - task: PowerShell@2
        displayName: 'Update Index.html file'
        inputs:
          filePath: '$(webAppName)\PowerShell\UpdateIndexHtml.ps1'
      - task: PowerShell@2
        displayName: 'Fix Service Worker Assets'
        inputs:
          filePath: '$(webAppName)\PowerShell\FixServiceWorkerAssets.ps1'
      - task: AzureCLI@2
        displayName: 'Remove Old Files'
        inputs:
          azureSubscription: '$(azureSubscription)'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: 'az storage blob delete-batch -s ''$web'' --account-name $(accountName)'
      - task: AzureFileCopy@2
        displayName: 'Copy Files to Azure Blob Storage'
        inputs:
          SourcePath: '$(System.DefaultWorkingDirectory)/$(webAppName)/bin/Release/net7.0/publish/wwwroot'
          azureSubscription: $(azureConnection)
          Destination: AzureBlob
          storage: $(accountName)
          ContainerName: '$web'
      - task: AzureCLI@2
        displayName: 'Set Correct Content-Type Attributes'
        inputs:
          azureSubscription: '$(azureSubscription)'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            $myloc = "$((Get-Location).ProviderPath)\$(webAppName)\bin\Release\net7.0\publish\wwwroot"
            Get-ChildItem "$(webAppName)\bin\Release\net7.0\publish\wwwroot" -Filter "*.wasm" -Recurse -Force | ForEach-Object {
                $rel_Path = $_.FullName.Replace($myloc, "").Replace("\","/")
                if ($rel_Path[0] -eq '/') {
                    $rel_Path = $rel_Path.Substring(1)
                }
                Write-Host "Updating Blob File: $($rel_Path)"
                az storage blob update -c '$web' -n $rel_Path --account-name $(accountName) --content-type application/wasm
            }
      - task: AzureCLI@2
        displayName: 'Purge Storage Cache'
        inputs:
          azureSubscription: $(azureConnection)
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: 'az cdn endpoint purge -g $(resourceGroup) -n $(accountName) --profile-name $(profileName) --content-paths ''/*'''

